###############################################
#
# Makefile
#
###############################################

cli:
	go run cli.go

svc:
	go run svc.go

mixed:
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors --allow-running-insecure-content https://localhost:8443/static/cors.html
